# copy from https://github.com/dart-lang/http/blob/master/analysis_options.yaml

include: package:flutter_lints/flutter.yaml

analyzer:
  # enable-experiment:
    # - non-nullable

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    constant_identifier_names: false
    prefer_final_locals: true
    prefer_single_quotes: true
    always_declare_return_types: true
    require_trailing_commas: true
    public_member_api_docs: true
