include: package:lints/recommended.yaml

analyzer:
  # enable-experiment:
    # - non-nullable

  strong-mode:
    implicit-dynamic: false

linter:
  rules:
    constant_identifier_names: false
    prefer_final_locals: true
    prefer_single_quotes: true
    always_declare_return_types: true
    require_trailing_commas: true
