include: package:lints/recommended.yaml
linter:
  rules:
    constant_identifier_names: false
    library_annotations: false
    prefer_final_locals: true
    prefer_single_quotes: true
    always_declare_return_types: true
    require_trailing_commas: true
